name: fdsn-prod
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      ecr-registry: 862640294325.dkr.ecr.ap-southeast-2.amazonaws.com
      role-arn-push: arn:aws:iam::862640294325:role/github-actions-geonet-ecr-push
      test-coverage-upload-role: arn:aws:iam::615890063537:role/tf-dev-github-actions-geonet-s3-coverage-fdsn
      test-coverage-upload-bucket: dev-geonet-webscan